cert: "tests/util/cert.pem"
key: "tests/util/key.pem"
trusted_peers: [
  "BTTVHUR-CKWU5YX-JMAULFO-5CMEQ36-FZWEWAE-QFXROCM-WKMOJPZ-KEUOWAS",
  "RFJWU2I-J6ULCCU-36JJOGP-YWEBZAB-T5KHSUO-ROXYHCJ-CUSRTBY-WKZHNQY",
  "5CLQ5SC-YWEKDFL-5BVSUPT-DGAP4DL-K4DDBSN-PEIIWEW-FJWWGVG-XEBIEQ2",
  "NFHDU7O-JJWVT6Z-UDI7CZB-ERU3YWF-BAECRZ5-KV46LMU-37YTU3G-JYCQ3AB"
]
base_dir: "tests/util/dest_dir"
db_url: "sqlite:tests/util/grizol.db"
storage_strategy: 1
rclone_config: "tests/util/rclone.conf.key"
remote_base_dir: "seravalli-grizol-testing"
mountpoint: "tests/util/fuse_mountpoint"
read_cache_dir: "tests/util/read_cache_dir"
read_cache_size: "100Mb"
fuse_refresh_rate_ms: 0
fuse_inmem: true 
