[package]
name = "mydama"
version = "0.0.1"
edition = "2021"
rust-version = "1.57"
license = "Apache-2.0 OR ISC OR MIT"
description = "Rustls example code and tests."
publish = false

[features]
dangerous_configuration = ["rustls/dangerous_configuration"]
quic = ["rustls/quic"]

[dependencies]
bytes = "1"
clap = { version ="4", features = ["derive"] }
env_logger = "0.9.0" # 0.10 requires an MSRV bump to 1.60
log = { version = "0.4.4" }
mio = { version = "0.8", features = ["net", "os-poll"] }
prost = "0.11"
prost-types = "0.11"
rustls-pemfile = "1.0.0"
rustls = { version = "0.21", features = [ "logging" ]}
sct = "0.7"
webpki-roots = "0.23"

[dev-dependencies]
regex = "1.0"
ring = "0.16.20"

[build-dependencies]
prost-build = { version = "0.11" }
